.\"	$OpenBSD$
.\"
.\" Copyright (c) 2015 Alexander Bluhm <bluhm@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt PTYPAIR 1
.Os
.Sh NAME
.Nm ptypair
.Nd bidirectional pipe through a pair of pseudo terminals
.Sh SYNOPSIS
.Nm ptypair
.Op Fl qv
.Sh DESCRIPTION
The
.Nm
utility creates two pseudo terminal devices.
All data is copied bidirectionally between them.
.Sh FILES
.Pa /dev/ttyp?
pseudo terminal device
.Sh EXIT STATUS
.Ex -std
.Sh DIAGNOSTICS
The name of both pseudo terminals is written to stdout prefixed
with
.Li PTY: .
Data read from a master pty is prefixed with
.Li >>>
and data written with
.Li <<< .
After all transfer has finished successfully, the number of bytes
is logged as
.Li READLEN:
and
.Li WRITELEN: .
To identify the pty, the master file descriptor is always logged
into the first column.
.Sh AUTHORS
The
.Nm
utility was written for the pipe and l4pipemux regression tests by
.An Alexander Bluhm Aq Mt bluhm@openbsd.org
